from __future__ import annotations

ETF_CATALOG = [
    {
        "code": "510300",
        "name": "沪深300ETF",
        "category": "宽基",
        "theme": "大盘核心资产",
        "benchmark": "沪深300指数",
        "risk_level": "平衡型",
        "description": "覆盖沪深两市核心龙头，兼具流动性与代表性，适合中长期配置。",
    },
    {
        "code": "510050",
        "name": "上证50ETF",
        "category": "宽基",
        "theme": "央国企蓝筹",
        "benchmark": "上证50指数",
        "risk_level": "稳健型",
        "description": "偏向大市值蓝筹和金融权重，波动相对可控，适合稳健型用户。",
    },
    {
        "code": "159915",
        "name": "创业板ETF",
        "category": "成长",
        "theme": "科技成长",
        "benchmark": "创业板指数",
        "risk_level": "积极型",
        "description": "聚焦成长风格和科技赛道，弹性较大，适合风险承受能力较强用户。",
    },
    {
        "code": "512100",
        "name": "中证1000ETF",
        "category": "宽基",
        "theme": "中小盘弹性",
        "benchmark": "中证1000指数",
        "risk_level": "积极型",
        "description": "对中小盘风格暴露更高，风格轮动收益弹性较强，但回撤也更明显。",
    },
    {
        "code": "515880",
        "name": "通信ETF",
        "category": "行业",
        "theme": "通信算力",
        "benchmark": "中证全指通信设备指数",
        "risk_level": "激进型",
        "description": "行业主题鲜明，受政策、订单和市场情绪影响更大，波动高于宽基 ETF。",
    },
    {
        "code": "510500",
        "name": "中证500ETF",
        "category": "宽基",
        "theme": "中盘均衡",
        "benchmark": "中证500指数",
        "risk_level": "平衡型",
        "description": "兼顾成长性与分散度，覆盖中盘核心资产，适合作为宽基配置的进阶补充。",
    },
    {
        "code": "588000",
        "name": "科创50ETF",
        "category": "成长",
        "theme": "硬科技创新",
        "benchmark": "科创50指数",
        "risk_level": "积极型",
        "description": "聚焦半导体、国产替代和高端制造，科技属性突出，适合看重创新弹性的用户。",
    },
    {
        "code": "515180",
        "name": "红利ETF",
        "category": "策略",
        "theme": "高股息红利",
        "benchmark": "中证红利指数",
        "risk_level": "稳健型",
        "description": "偏向现金流稳定和分红能力较强的龙头公司，防御属性更强，适合稳健配置。",
    },
]
